stages:
  - build
  - deploy

variable:
  GLOBAL_VAR: "3.0"

criar_imagens:
  stage: build
  tags:
    - test
  script:
  - docker build -t goncalves878/my-docker-devops:$GLOBAL_VAR app/.
  - docker push goncalves878/my-docker-devops:$GLOBAL_VAR

executar_imagens:
  stage: deploy
  needs:
    - criar_imagens
  tags:
    - test
  before_script:
  - docker rm $(docker ps -a -q) --force
  script:
  - docker run -dti --name web-server -p 80:80 goncalves878/my-docker-devops:$GLOBAL_VAR
  after_script:
  - docker system prune --force