stages:
  - build
  - deploy


criar_imagens:
  stage: build
  tags:
    - gcp
  script:
  - docker build -t goncalves878/my-docker-devops app/.
  - docker push goncalves878/my-docker-devops

kubernetes:
  stage: deploy
  needs:
    - criar_imagens
  tags:
    - gcp
  script:
  - kubectl apply -f ./deploy-micro1.yml
